pipeline {

        agent node


            def remote = [:]
            remote.name = 'test'
            remote.host = '192.168.33.11'
            remote.user = 'jenkins'
            remote.allowAnyHosts = true
            stage('Remote SSH') {
              sshCommand remote: remote, command: "ls -lrt"
            }


    
}
