def build_docker_image() {
    return {
        stage("Building image"){
            echo "Build Docker Image devopsabi/demo_app:${new_version} "
            echo "${env}"
            
            script{
                withDockerRegistry(url:'',credentialsId:'docker_hub_id'){
                    current_deploy_version = sh (returnStdout: true, script: 'cat new_version.txt').trim()
                    docker.build('devopsabi/demo_app:'+current_deploy_version).push()
                }
            }
            
            
            
        }
    }
}

def update_app() {
    return {
        stage("Updating app to ${new_version}")
        new_version = sh(script: 'cat new_version.txt', returnStdout: true)
        deploy_app = 'docker service update --image devopsabi/demo_app:\'+new_version +\' demo_app'
        echo ${deploy_app}
    }
}

def success_call(docker_img) {
    return {
        stage("Building Docker Image"){
            echo "Build Docker Image ${docker_img}"
            
        }
    }
}


 
 pipeline {
        agent any
        
        stages {
        
            stage('checkout_nodejs_app') {
                steps {
                    git branch:"master", url: '', credentialsId:'git_hub_id'
                }
    
            }

		
         stage('build docker image nodejs_app'){
                steps {
                    script{
                            status = sh(script: 'cat deploy.txt', returnStdout: true).trim()
                            current_version = sh(script: 'cat current_version.txt', returnStdout: true)
                            new_version = sh(script: 'cat new_version.txt', returnStdout: true)
                            println "${status}"
                            if ( status == 'no' ){
                                    println "NOT DEPLOYING THE CHANGES... Please update deploy.txt and set as "yes" If you would like to deploy the current version "
                                    success_call('img_abhi').call()
                                }
                                
                            if ( status == 'yes' ){
                                    println "current Version = ${current_version}\nNew version = ${new_version}"
                                    build_docker_image().call()
                                    update_app().call()
                                }
                    
                    }
                }
            }
            
        
            

	    stage('Test Run') {
            	steps {
                	retry(3) {
                  	  sh './run.sh'
               		 }

                	timeout(time: 3, unit: 'MINUTES') {
                    		sh './health-check.sh'
               		 }
            	}
	    }

    }
}
